# Generated by Django 4.2.1 on 2023-06-07 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0007_remove_balltofile_author_balltofile_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penaltyuplaodfile',
            name='author',
        ),
        migrations.AddField(
            model_name='penaltyuplaodfile',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Avtor'),
        ),
    ]
